### ISSUE TITLE
IP does not match.

### ISSUE THREAD

**Issue by poke1337** [Promptitude/zaz-gmod#12]
The IP that get set for the server list does not match the real IP.

This leads the connect button on the server list to do nothing, or it is trying to connect to a invalid server.

**Comment by Promptitude** [comment]
This isn't an error on the Lua side. However, we can speak about adding this.

**Comment by poke1337** [comment]
Change the IP that goes into server list but keeping the way we check IPs.

Needs testing now.

**Comment by poke1337** [comment]
Change the way we store IP's.

Use the API type 3 with the argument of `ip` to store the IP of a server.

- [ ] Change addon to use the new API argument of `ip`
- [ ] Change the API to accept a argument of `ip` and set the servers IP to be that in the server list.
